#+ endpoint: https://triplestore.coronawhy.org/nowmuseum/sparql

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <https://schema.org/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX citation: <https://dataverse.org/schema/citation/>
PREFIX ore: <http://www.openarchives.org/ore/1.0/terms/>
PREFIX id: <https://doi.org/>
SELECT ?keyword (COUNT(?keyword) AS ?keywordCount)
WHERE {
 ?id schema:distribution ?url;
        dcterms:title ?title;
        citation:dsDescription ?description;
    citation:productionPlace ?country;
        citation:keyword ?keywordID.
 ?description citation:dsDescriptionValue ?summary.
 ?keywordID citation:keywordValue ?keyword.
}
GROUP BY ?keyword
ORDER BY DESC(?keywordCount)
