#+ endpoint: https://triplestore.coronawhy.org/disabilities/sparql

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
PREFIX schemas: <https://schema.org/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX citation: <https://dataverse.org/schema/citation/>
PREFIX ore: <http://www.openarchives.org/ore/1.0/terms/>
SELECT DISTINCT ?url ?title ?description 
WHERE {
 ?id schema:name ?title;
     schemas:distribution ?url;
     citation:dsDescription ?descid.
 ?descid ?desctype ?description.
}
LIMIT 200
